class CfgPatches
{
	class sia_faction_medu
	{
		units[]=
		{
			"sia_medu_base",
            "sia_medu_rifleman",
			"sia_medu_grenadier",
			"sia_medu_rifleman_lat",
			"sia_medu_specialist_at",
			"sia_medu_autorifleman",
			"sia_medu_machinegunner",
			"sia_medu_marksman",
			"sia_medu_officer",
			"sia_medu_officer_combat",
			"sia_medu_squadleader",
			"sia_medu_teamleader",
			"sia_medu_medic",
			"sia_medu_engineer",
			"sia_medu_crewman",
			"sia_medu_crew_commander",
			"sia_medu_helipilot",
			"sia_medu_helicrew",
			"sia_medu_sniper",
			"sia_medu_spotter",
			"sia_medu_sf_rifleman",
			"sia_medu_sf_grenadier",
			"sia_medu_sf_rifleman_lat",
			"sia_medu_sf_specialist_at",
			"sia_medu_sf_autorifleman",
			"sia_medu_sf_machinegunner",
			"sia_medu_sf_marksman",
			"sia_medu_sf_officer",
			"sia_medu_sf_squadleader",
			"sia_medu_sf_teamleader",
			"sia_medu_sf_medic",
			"sia_medu_sf_engineer",
			"sia_medu_sf2_rifleman", 
			"sia_medu_sf2_grenadier", 
			"sia_medu_sf2_rifleman_lat", 
			"sia_medu_sf2_specialist_at", 
			"sia_medu_sf2_autorifleman", 
			"sia_medu_sf2_machinegunner", 
			"sia_medu_sf2_marksman", 
			"sia_medu_sf2_teamleader", 
			"sia_medu_sf2_squadleader", 
			"sia_medu_sf2_engineer"
		};
		weapons[] = {};
		requiredVersion=1.62;
		requiredAddons[]={"A3_Characters_F"};
	};
};